"""
Regenerate backend/test/fixtures/refine9-golden.json: a small synthetic image with its
cv2 CLAHE and torchvision antialiased resize, the two steps of refine9's val_transform that
the Node port re-implements (backend/src/bone-age/refine9.preprocess.ts).

    venv/bin/pip install opencv-python-headless && venv/bin/python golden.py
"""
import base64
import json
from pathlib import Path

import cv2
import numpy as np
import torch
import torchvision.transforms.functional as TF

OUT = Path(__file__).resolve().parents[2] / 'backend/test/fixtures/refine9-golden.json'

rng = np.random.default_rng(7)
H, W = 120, 90  # 90 is not a multiple of 8, so OpenCV's tile padding is exercised
y, x = np.mgrid[0:H, 0:W]
img = (40 + 120 * np.exp(-((x - 45) ** 2 / 300 + (y - 60) ** 2 / 900))
       + rng.normal(0, 12, (H, W))).clip(0, 255).astype(np.uint8)
cl = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8)).apply(img)
rs = TF.resize(torch.from_numpy(cl).unsqueeze(0), [45, 45], antialias=True)[0].numpy()


def b64(a):
    return base64.b64encode(a.tobytes()).decode()


OUT.write_text(json.dumps({
    'note': f'cv2 {cv2.__version__}, torchvision; generated by ai-service/refine9/golden.py',
    'h': H, 'w': W, 'input': b64(img), 'clahe': b64(cl), 'resized45': b64(rs),
}))
print('wrote', OUT)
